### ISSUE TITLE
Feature request: render sphinx markup in description attributes of fields

### ISSUE THREAD

**Issue by iliakur** [mansenfranzen/autodoc_pydantic#91] opened 2022-01-26 08:16 UTC
Hi!

Thanks for this very nice tool! It's so nice, that I'm wondering if we can make it even more powerful :)

Would it be a challenge to render any sphinx markup in the `description` attribute of a `Field`?

I'd love to help, but afraid that I'm a bit low on free time for the next month or two.

**Comment by mansenfranzen** [comment] 2022-01-26 09:08
@iliakur thanks for your proposal. It totally makes sense and actually it should be the default behavior because standard doc strings are treated and interpreted as sphinx extended reST. Therefore, the same should apply to explicitly added documentation via the `description` attribute. 

The `description` attribute of pydantic `Field`s already support inline reST. However, line breaks are not interpreted correctly. Hence, you can use `:any:` for example, but field lists á la `:fieldname: some value` won't work properly. 

Having a quick look into sphinx' source code, we will need to pass the `description` content to [prepare_docstring](https://github.com/sphinx-doc/sphinx/blob/e54b63d3eead95ef3fac1906deae54b6972573e4/sphinx/util/docstrings.py#L60) in order to get separate lines of reST (which respects line breaks). 

I will take a closer look at it soonish. It should not be too difficult to implement.

**Comment by iliakur** [comment] 2022-01-26 12:31
Thanks for the fast response! Indeed I forgot to mention that I have successfully used inline reST in a description and it was just multi-line directives that were missing.

I'm glad this is likely easy to add, looking forward to using it!

**Comment by mansenfranzen** [comment] 2022-01-28 22:17
@all-contributors please add @iliakur for bug

**Comment by mansenfranzen** [comment] 2022-01-28 22:30
Issue has been fixed with #92 and minor release v1.6.1 is already up on pypi. Reproducing the bug in a test case and fixing it was not difficult. Please check if you experience the correct behavior with the most recent version to ensure that I captured your problem correctly.

Feel free to reopen the issue if it persists and thanks for reporting once again!

**Closed by mansenfranzen** 2022-01-28 22:30 UTC
Labels: bug

**Comment by iliakur** [comment] 2022-01-29 09:53
Wow, some pretty impressive automation you got there ;)

Thanks for the fix (didn't realize this was a bug :joy: ), I'm excited to try it out next week!

**Comment by iliakur** [comment] 2022-02-07 12:05
Used it last week, works swimmingly, thanks!
