### ISSUE TITLE
autosummary does not seem to work with autodoc_pydantic 

### ISSUE THREAD

**Issue by antvig** [mansenfranzen/autodoc_pydantic#11] opened 2021-04-30 17:07 UTC
Hi

First, my doc and I would like to thank you a lot for this great lib !

I face an issue : I'm using `autosummary` to have a clean doc but using autodoc_pydantic seem not compatible with `autosummary`

```
.. currentmodule:: my_module

API Reference
=============

This page gives an overview of all public :mod:`my_module` objects, functions and methods. 

all classes
+++++++++++

.. autosummary::
   :toctree: temp
   :nosignatures:
   :inherited-members:

   ForecastingConfig

```

the results is 

![image](https://user-images.githubusercontent.com/25105210/116729026-f56bff80-a9e6-11eb-831c-e7aeac884c74.png)

While the results before using `autodoc_pydantic` was : 

![image](https://user-images.githubusercontent.com/25105210/116729216-3401ba00-a9e7-11eb-8e5a-e4b6652740a3.png)

**Comment by mansenfranzen** [comment] 2021-04-30 20:15
Hi, 

thanks for reporting the issue. This is definitely a bug related to autosummary while also using `sphinx-autogen`. If you use it without `sphinx-autogen` and `:toctree: temp` it works for me (sphinx 3.5.4). What sphinx version do you use?

The real issue is located within the autogen part. This seems rather complicated to fix for now. I will get back to it, soon.

**Comment by mansenfranzen** [comment] 2021-05-02 14:40
The issue is related to how `autosummary` parses the autodocumenters via `FakeDirective`. It assumes that autodocumenters have no configuration parameters read from the app environment. This is the default case for standard autodocumenters but not for `autodoc_pydantic`. The issue should be fixed with the new dev version `1.1.2_dev` (see #13). However, before I merge those changes including tests, please test it locally on your site. To do so, just install the dev version into your documentation build environment via:

```bash
pip install git+git://github.com/mansenfranzen/autodoc_pydantic.git@v1.1.2_dev
```

**Comment by antvig** [comment] 2021-05-03 11:45
Hi,

Unfortunatly, it's still not working.

I use `sphinx==3.5.4`, `autosummary` files are generated with `sphinx-build` command.

here is the 2 files generated during `sphinx-build` with  and without `autodoc_pydantic` [test.zip](https://github.com/mansenfranzen/autodoc_pydantic/files/6414560/test.zip)`

**Comment by mansenfranzen** [comment] 2021-05-03 14:13
Thanks for testing. Do you see any difference in the logging output provided by **sphinx-build** (warnings or error messages) when using it with `autodoc_pydantic`? 

I assume you have `autosummary_generate = True` in your `conf.py`, right? The files you've provided are the stub files generated by **sphinx-autogen**. They are indeed still different because sphinx-autogen only knows about the default autodocumenters. However, the `autosummary` table that is generated should now contain your `ForecastingConfig` entry.

Do you have your project on github? This way I could reproduce the bug directly. It works in my local repository.

**Comment by antvig** [comment] 2021-05-03 14:32
Unfortunatly, it's related to my professional job so I cannot share the repo.

I'll try in the following days to make a short example to reproduce the bug.

**Comment by antvig** [comment] 2021-05-03 17:03
[issue.zip](https://github.com/mansenfranzen/autodoc_pydantic/files/6416392/issue.zip)

to reproduce : `sphinx-build "source" "build"`

**Comment by mansenfranzen** [comment] 2021-05-04 11:15
Thanks for the example repository - it finally helped me to track down one of the errors you are experiencing 👍. 

### autosummary - toc - import bug

More concretely, your example imports the relevant pydantic model into the `__init__` module and the `autosummary` directive references the pydantic model from the `__init__` module instead from `mymodule.core`. The imports in autosummary/autodoc are somewhat non trivial - hence such a bug. It is now fixed. The autosummary toc will now show the `MyModel`.

### interoperability autosummary - custom autodocumenters

However, there is a second issue. Namely, `autosummary` does not integrate well with custom autodocumenter extensions when generating the stub pages (see this [issue](https://github.com/sphinx-doc/sphinx/issues/6264)). I updated the documentation for autosummary usage and included a warning (please take a look [here](https://autodoc-pydantic.readthedocs.io/en/fix_autosummary/usage.html#autosummary)).

### final test

To test the newest version, please use the following:

```
pip install git+git://github.com/mansenfranzen/autodoc_pydantic.git@v1.1.2-a.1
```

It would be very helpful if you could test it once again on your site.

**Comment by antvig** [comment] 2021-05-06 07:50
it works like a charm! 👍 
Let me know when the patch is released !

**Comment by mansenfranzen** [comment] 2021-05-06 08:34
Thanks for testing! Patch is released. 

Closing this issue via #13.

**Closed by mansenfranzen** 2021-05-06 08:34 UTC
Labels: bug
